version: '3.1'
services:
    postgres-db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres # locale password for testing
        ports: 
        - 5432:5432

     adminer:
         image: adminer
         restart: always
         ports:
         - 3100:8080