drop table IF EXISTS TRACKING;
drop table IF EXISTS ORDERS;


CREATE TABLE ORDERS(
    ID SERIAL PRIMARY KEY,
    SOURCE VARCHAR(128) NOT NULL,
    DESTINATION VARCHAR(128) NOT NULL,
    STATUS VARCHAR(64) NOT NULL,
    DELIVERY_TIME timestamptz,
    NO_OF_PKGS INTEGER NOT NULL,
    WEIGHT INTEGER ,
    VOLUME INTEGER ,
    CREATE_TIME timestamptz NOT NULL,
    UPDATE_TIME timestamptz
);

CREATE TABLE TRACKING(
    ID SERIAL,
    UPDATE_TIME timestamptz NOT NULL,
    LOCATION VARCHAR(256) NOT NULL,
    MESSAGE VARCHAR(256) NOT NULL,
    ORDER_ID INTEGER NOT NULL,
    CONSTRAINT FK_ORDER
        FOREIGN KEY(ORDER_ID)
            REFERENCES ORDERS(ID)
);